name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  schedule:
    - cron: '30 2 * * *'
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install chrome --with-deps

      - name: Run Playwright tests
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          USERNAME_PPM: ${{ secrets.USERNAME_PPM }}
          PASSWORD_PPM: ${{ secrets.PASSWORD_PPM }}
        run: npx playwright test tests/main.ts

